// <auto-generated>
//  This code was generated by the following tool on 2023-08-10 00:50:37 GMT+00:00:
//      https://github.com/bottlenoselabs/c2cs (v6.1.3.0)
//
//  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ReSharper disable All

#region Template
#nullable enable
#pragma warning disable CS1591
#pragma warning disable CS8981
using bottlenoselabs.C2CS.Runtime;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
#endregion

public static unsafe partial class PInvoke
{
    private const string LibraryName = "PInvoke";

    #region API

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsAlertsImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsAlertsImport(ecs_world_t* world);

     [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsCoreDocImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsCoreDocImport(ecs_world_t* world);

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsDocImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsDocImport(ecs_world_t* world);

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsMetaImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsMetaImport(ecs_world_t* world);

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsMetricsImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsMetricsImport(ecs_world_t* world);

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsMonitorImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsMonitorImport(ecs_world_t* world);

    [CNode(Kind = "Function")]
    [LibraryImport(LibraryName, EntryPoint = "FlecsPipelineImport")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void FlecsPipelineImport(ecs_world_t* world);

    public struct Coords
    {
        public CString Pointer;
        public delegate* unmanaged<CString, CString> Pointer2;
    }

        [CNode(Kind = "TypeAlias")]
        [StructLayout(LayoutKind.Explicit, Size = 8, Pack = 8)]
        public struct ecs_app_frame_action_t
        {
            [FieldOffset(0)]
            public FnPtr_EcsWorldTPtr_EcsAppDescTPtr_Int Data;

            public static implicit operator FnPtr_EcsWorldTPtr_EcsAppDescTPtr_Int(ecs_app_frame_action_t data) => data.Data;
            public static implicit operator ecs_app_frame_action_t(FnPtr_EcsWorldTPtr_EcsAppDescTPtr_Int data) => new() { Data = data };
        }
}
